main: function_declarations.h read_sparse_matrix_from_file.c sampled_matrix_multiplication_coo.c sampled_matrix_multiplication_crs.c translate_coo_to_crs.c 
	gcc -o main main.c read_sparse_matrix_from_file.c sampled_matrix_multiplication_coo.c sampled_matrix_multiplication_crs.c translate_coo_to_crs.c

parallel: function_declarations.h read_sparse_matrix_from_file.c sampled_matrix_multiplication_coo.c sampled_matrix_multiplication_crs.c translate_coo_to_crs.c 
	gcc -fopenmp -o main main.c read_sparse_matrix_from_file.c sampled_matrix_multiplication_coo.c sampled_matrix_multiplication_crs.c translate_coo_to_crs.c